//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.2 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2022.05.26 at 01:04:52 AM CAT 
//


package za.co.ominsure.synapse.internal.lucene.backend.products.vo;

import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for Product complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="Product"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="sequenceNo" type="{http://www.w3.org/2001/XMLSchema}long"/&gt;
 *         &lt;element name="segment" type="{http://synapse.ominsure.co.za/lob/pricing/backend/lucene/vo}NameCode"/&gt;
 *         &lt;element name="family" type="{http://synapse.ominsure.co.za/lob/pricing/backend/lucene/vo}NameCode"/&gt;
 *         &lt;element name="class" type="{http://synapse.ominsure.co.za/lob/pricing/backend/lucene/vo}NameCode"/&gt;
 *         &lt;element name="commodity" type="{http://synapse.ominsure.co.za/lob/pricing/backend/lucene/vo}NameCode"/&gt;
 *         &lt;element name="itemCode" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;element name="stockCode" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="brand" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;element name="shortDescription" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;element name="longDescription" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;element name="removed" type="{http://synapse.ominsure.co.za/lob/pricing/backend/lucene/vo}YN"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "Product", propOrder = {
    "sequenceNo",
    "segment",
    "family",
    "productClass",
    "commodity",
    "itemCode",
    "stockCode",
    "brand",
    "shortDescription",
    "longDescription",
    "removed"
})
public class Product {

    protected long sequenceNo;
    @XmlElement(required = true)
    protected NameCode segment;
    @XmlElement(required = true)
    protected NameCode family;
    @XmlElement(required = true)
    protected NameCode productClass;
    @XmlElement(required = true)
    protected NameCode commodity;
    @XmlElement(required = true)
    protected String itemCode;
    protected String stockCode;
    @XmlElement(required = true)
    protected String brand;
    @XmlElement(required = true)
    protected String shortDescription;
    @XmlElement(required = true)
    protected String longDescription;
    @XmlElement(required = true)
    @XmlSchemaType(name = "string")
    protected YN removed;

    /**
     * Gets the value of the sequenceNo property.
     * 
     */
    public long getSequenceNo() {
        return sequenceNo;
    }

    /**
     * Sets the value of the sequenceNo property.
     * 
     */
    public void setSequenceNo(long value) {
        this.sequenceNo = value;
    }

    /**
     * Gets the value of the segment property.
     * 
     * @return
     *     possible object is
     *     {@link NameCode }
     *     
     */
    public NameCode getSegment() {
        return segment;
    }

    /**
     * Sets the value of the segment property.
     * 
     * @param value
     *     allowed object is
     *     {@link NameCode }
     *     
     */
    public void setSegment(NameCode value) {
        this.segment = value;
    }

    /**
     * Gets the value of the family property.
     * 
     * @return
     *     possible object is
     *     {@link NameCode }
     *     
     */
    public NameCode getFamily() {
        return family;
    }

    /**
     * Sets the value of the family property.
     * 
     * @param value
     *     allowed object is
     *     {@link NameCode }
     *     
     */
    public void setFamily(NameCode value) {
        this.family = value;
    }

    /**
     * Gets the value of the clazz property.
     * 
     * @return
     *     possible object is
     *     {@link NameCode }
     *     
     */
    public NameCode getProductClass() {
        return productClass;
    }

    /**
     * Sets the value of the clazz property.
     * 
     * @param value
     *     allowed object is
     *     {@link NameCode }
     *     
     */
    public void setProductClass(NameCode value) {
        this.productClass = value;
    }

    /**
     * Gets the value of the commodity property.
     * 
     * @return
     *     possible object is
     *     {@link NameCode }
     *     
     */
    public NameCode getCommodity() {
        return commodity;
    }

    /**
     * Sets the value of the commodity property.
     * 
     * @param value
     *     allowed object is
     *     {@link NameCode }
     *     
     */
    public void setCommodity(NameCode value) {
        this.commodity = value;
    }

    /**
     * Gets the value of the itemCode property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getItemCode() {
        return itemCode;
    }

    /**
     * Sets the value of the itemCode property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setItemCode(String value) {
        this.itemCode = value;
    }

    /**
     * Gets the value of the stockCode property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getStockCode() {
        return stockCode;
    }

    /**
     * Sets the value of the stockCode property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setStockCode(String value) {
        this.stockCode = value;
    }

    /**
     * Gets the value of the brand property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getBrand() {
        return brand;
    }

    /**
     * Sets the value of the brand property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setBrand(String value) {
        this.brand = value;
    }

    /**
     * Gets the value of the shortDescription property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getShortDescription() {
        return shortDescription;
    }

    /**
     * Sets the value of the shortDescription property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setShortDescription(String value) {
        this.shortDescription = value;
    }

    /**
     * Gets the value of the longDescription property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getLongDescription() {
        return longDescription;
    }

    /**
     * Sets the value of the longDescription property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setLongDescription(String value) {
        this.longDescription = value;
    }

    /**
     * Gets the value of the removed property.
     * 
     * @return
     *     possible object is
     *     {@link YN }
     *     
     */
    public YN getRemoved() {
        return removed;
    }

    /**
     * Sets the value of the removed property.
     * 
     * @param value
     *     allowed object is
     *     {@link YN }
     *     
     */
    public void setRemoved(YN value) {
        this.removed = value;
    }

}
