//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.2 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2022.06.01 at 10:29:54 PM CAT 
//


package za.co.ominsure.synapse.internal.lucene.backend.vo;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for CRUDIndexingRequest complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="CRUDIndexingRequest"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="indexName" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;element name="keyName" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;element name="fieldName" type="{http://www.w3.org/2001/XMLSchema}string" maxOccurs="unbounded"/&gt;
 *         &lt;element name="tableInfo" type="{http://synapse.ominsure.co.za/internal/lucene/backend/vo}TableInfo" minOccurs="0"/&gt;
 *         &lt;element name="attributes" type="{http://synapse.ominsure.co.za/internal/lucene/backend/vo}Attribute" maxOccurs="unbounded" minOccurs="0"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "CRUDIndexingRequest", propOrder = {
    "indexName",
    "keyName",
    "fieldName",
    "tableInfo",
    "attributes"
})
public class CRUDIndexingRequest {

    @XmlElement(required = true)
    protected String indexName;
    @XmlElement(required = true)
    protected String keyName;
    @XmlElement(required = true)
    protected List<String> fieldName;
    protected TableInfo tableInfo;
    protected List<Attribute> attributes;

    /**
     * Gets the value of the indexName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getIndexName() {
        return indexName;
    }

    /**
     * Sets the value of the indexName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setIndexName(String value) {
        this.indexName = value;
    }

    /**
     * Gets the value of the keyName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getKeyName() {
        return keyName;
    }

    /**
     * Sets the value of the keyName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setKeyName(String value) {
        this.keyName = value;
    }

    /**
     * Gets the value of the fieldName property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the fieldName property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getFieldName().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link String }
     * 
     * 
     */
    public List<String> getFieldName() {
        if (fieldName == null) {
            fieldName = new ArrayList<String>();
        }
        return this.fieldName;
    }

    /**
     * Gets the value of the tableInfo property.
     * 
     * @return
     *     possible object is
     *     {@link TableInfo }
     *     
     */
    public TableInfo getTableInfo() {
        return tableInfo;
    }

    /**
     * Sets the value of the tableInfo property.
     * 
     * @param value
     *     allowed object is
     *     {@link TableInfo }
     *     
     */
    public void setTableInfo(TableInfo value) {
        this.tableInfo = value;
    }

    /**
     * Gets the value of the attributes property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the attributes property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getAttributes().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link Attribute }
     * 
     * 
     */
    public List<Attribute> getAttributes() {
        if (attributes == null) {
            attributes = new ArrayList<Attribute>();
        }
        return this.attributes;
    }

	public void setFieldName(List<String> fieldName) {
		this.fieldName = fieldName;
	}

	public void setAttributes(List<Attribute> attributes) {
		this.attributes = attributes;
	}

}
