//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.2 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2022.06.01 at 10:29:54 PM CAT 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "http://synapse.ominsure.co.za/internal/lucene/backend/vo", elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED)
package za.co.ominsure.synapse.internal.lucene.backend.vo;
